#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Jan 28, 2016 01:49:40 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab62
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 671x450+668+291
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1680 1001
    wm minsize $top 72 15
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "SH Mobot Configuration"
    vTcl:DefineAlias "$top" "SHParaToplevel" vTcl:Toplevel:WidgetProc "" 1
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Apply Configuration} 
    vTcl:DefineAlias "$top.but40" "configButton" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::scale $top.tSc43 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tSc43" "TScale1" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::progressbar $top.tPr44
    vTcl:DefineAlias "$top.tPr44" "TProgressbar1" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab45 \
        -background {#d9d9d9} -foreground {#000000} -text {Mobot Battery} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::scale $top.tSc46 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tSc46" "TScale2" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::scale $top.tSc47 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tSc47" "TScale3" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab48 \
        -background {#d9d9d9} -foreground {#000000} -justify right -text Blur 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab49 \
        -background {#d9d9d9} -foreground {#000000} -justify right \
        -text {Canny Lo} 
    vTcl:DefineAlias "$top.lab49" "Label3" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab50 \
        -background {#d9d9d9} -foreground {#000000} -justify right \
        -text {Canny Hi} 
    vTcl:DefineAlias "$top.lab50" "Label4" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab51 \
        -background {#d9d9d9} -foreground {#000000} -justify right \
        -text Saturation 
    vTcl:DefineAlias "$top.lab51" "Label5" vTcl:WidgetProc "SHParaToplevel" 1
    label $top.lab52 \
        -background {#d9d9d9} -foreground {#000000} -justify right \
        -text Brightness 
    vTcl:DefineAlias "$top.lab52" "Label6" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::scale $top.tSc53 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tSc53" "TScale4" vTcl:WidgetProc "SHParaToplevel" 1
    ttk::scale $top.tSc54 \
        -takefocus {} 
    vTcl:DefineAlias "$top.tSc54" "TScale5" vTcl:WidgetProc "SHParaToplevel" 1
    checkbutton $top.che55 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text MedianBlur -variable che55 
    vTcl:DefineAlias "$top.che55" "Checkbutton1" vTcl:WidgetProc "SHParaToplevel" 1
    checkbutton $top.che56 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {Line Approx.} -variable che56 
    vTcl:DefineAlias "$top.che56" "Checkbutton2" vTcl:WidgetProc "SHParaToplevel" 1
    checkbutton $top.che57 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {Mobot Action} -variable che57 
    vTcl:DefineAlias "$top.che57" "Checkbutton3" vTcl:WidgetProc "SHParaToplevel" 1
    checkbutton $top.che58 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Inspection -variable che58 
    vTcl:DefineAlias "$top.che58" "Checkbutton4" vTcl:WidgetProc "SHParaToplevel" 1
    checkbutton $top.che59 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {System Stats} -variable che59 
    vTcl:DefineAlias "$top.che59" "Checkbutton5" vTcl:WidgetProc "SHParaToplevel" 1
    labelframe $top.lab62 \
        -foreground black -text Connection -background {#d9d9d9} -height 125 \
        -width 380 
    vTcl:DefineAlias "$top.lab62" "Labelframe1" vTcl:WidgetProc "SHParaToplevel" 1
    set site_3_0 $top.lab62
    button $site_3_0.but63 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Connect 
    vTcl:DefineAlias "$site_3_0.but63" "Button3" vTcl:WidgetProc "SHParaToplevel" 1
    button $site_3_0.but64 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Disconnect 
    vTcl:DefineAlias "$site_3_0.but64" "Button4" vTcl:WidgetProc "SHParaToplevel" 1
    button $site_3_0.but65 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Ping 
    vTcl:DefineAlias "$site_3_0.but65" "Button5" vTcl:WidgetProc "SHParaToplevel" 1
    entry $site_3_0.ent66 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry1" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab67 \
        -background {#d9d9d9} -foreground {#000000} -text {IP ADDR} 
    vTcl:DefineAlias "$site_3_0.lab67" "Label7" vTcl:WidgetProc "SHParaToplevel" 1
    label $site_3_0.lab68 \
        -background {#d9d9d9} -foreground {#000000} -text PORT 
    vTcl:DefineAlias "$site_3_0.lab68" "Label8" vTcl:WidgetProc "SHParaToplevel" 1
    entry $site_3_0.ent70 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent70" "Entry2" vTcl:WidgetProc "SHParaToplevel" 1
    place $site_3_0.but63 \
        -in $site_3_0 -x 200 -y 90 -width 80 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 280 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 10 -y 90 -width 75 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 70 -y 20 -width 252 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 10 -y 20 -width 53 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 10 -y 50 -width 53 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent70 \
        -in $site_3_0 -x 70 -y 50 -width 72 -height 27 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab71 \
        -foreground black -text {System Status} -background {#d9d9d9} \
        -height 165 -width 260 
    vTcl:DefineAlias "$top.lab71" "Labelframe2" vTcl:WidgetProc "SHParaToplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but40 \
        -in $top -x 190 -y 390 -width 164 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tSc43 \
        -in $top -x 90 -y 190 -anchor nw -bordermode ignore 
    place $top.tPr44 \
        -in $top -x 0 -y 430 -width 670 -height 16 -anchor nw \
        -bordermode ignore 
    place $top.lab45 \
        -in $top -x 10 -y 400 -width 103 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tSc46 \
        -in $top -x 90 -y 230 -anchor nw -bordermode ignore 
    place $top.tSc47 \
        -in $top -x 90 -y 270 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 190 -width 65 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 230 -width 67 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 10 -y 270 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab51 \
        -in $top -x 10 -y 310 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.lab52 \
        -in $top -x 10 -y 350 -width 63 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.tSc53 \
        -in $top -x 90 -y 310 -anchor nw -bordermode ignore 
    place $top.tSc54 \
        -in $top -x 90 -y 350 -anchor nw -bordermode ignore 
    place $top.che55 \
        -in $top -x 370 -y 190 -width 97 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.che56 \
        -in $top -x 410 -y 20 -anchor nw -bordermode ignore 
    place $top.che57 \
        -in $top -x 410 -y 50 -width 127 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.che58 \
        -in $top -x 410 -y 80 -anchor nw -bordermode ignore 
    place $top.che59 \
        -in $top -x 410 -y 110 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 20 -y 10 -width 380 -height 125 -anchor nw \
        -bordermode ignore 
    place $top.lab71 \
        -in $top -x 380 -y 230 -width 260 -height 165 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

